/* @flow */

export const
  OPEN_EDIT_PLANNED_TRANSACTION_DIALOG: 'OPEN_EDIT_PLANNED_TRANSACTION_DIALOG' =
    'OPEN_EDIT_PLANNED_TRANSACTION_DIALOG',
  EDIT_PLANNED_TRANSACTION_CLOSE_DIALOG: 'EDIT_PLANNED_TRANSACTION_CLOSE_DIALOG' =
    'EDIT_PLANNED_TRANSACTION_CLOSE_DIALOG',
  EDIT_PLANNED_TRANSACTION_DIALOG_CONFIRM_BP: 'EDIT_PLANNED_TRANSACTION_DIALOG_CONFIRM_BP'
    = 'EDIT_PLANNED_TRANSACTION_DIALOG_CONFIRM_BP',
  EDIT_PLANNED_TRANSACTION_DIALOG_AMOUNT_CHANGED: 'EDIT_PLANNED_TRANSACTION_DIALOG_AMOUNT_CHANGED' =
    'EDIT_PLANNED_TRANSACTION_DIALOG_AMOUNT_CHANGED',
  EDIT_PLANNED_TRANSACTION_DIALOG_REPEAT_EVERY_MONTH_PRESSED: 'EDIT_PLANNED_TRANSACTION_DIALOG_REPEAT_EVERY_MONTH_PRESSED' // eslint-disable-line max-len
    = 'EDIT_PLANNED_TRANSACTION_DIALOG_REPEAT_EVERY_MONTH_PRESSED',
  EDIT_PLANNED_TRANSACTION_DIALOG_COMMENT_CHANGED: 'EDIT_PLANNED_TRANSACTION_DIALOG_COMMENT_CHANGED'
    = 'EDIT_PLANNED_TRANSACTION_DIALOG_COMMENT_CHANGED',
  EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_CHANGED: 'EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_CHANGED' =
    'EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_CHANGED',
  EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_TEXT_CHANGED: 'EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_TEXT_CHANGED' // eslint-disable-line max-len
    = 'EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_TEXT_CHANGED',
  EDIT_PLANNED_TRANSACTION_DIALOG_CURRENCY_PRESS: 'EDIT_PLANNED_TRANSACTION_DIALOG_CURRENCY_PRESS' =
    'EDIT_PLANNED_TRANSACTION_DIALOG_CURRENCY_PRESS',
  EDIT_PLANNED_TRANSACTION_DIALOG_CANCEL_BP: 'EDIT_PLANNED_TRANSACTION_DIALOG_CANCEL_BP'
    = 'EDIT_PLANNED_TRANSACTION_DIALOG_CANCEL_BP',
  EDIT_PLANNED_DAY_PRESSED: 'EDIT_PLANNED_DAY_PRESSED'
    = 'EDIT_PLANNED_DAY_PRESSED'

type OpenPlannedTransactionProps = {| transactionId: string |}

type OpenPlannedTransactionAction = {|
  type: typeof OPEN_EDIT_PLANNED_TRANSACTION_DIALOG,
  ...OpenPlannedTransactionProps
|}

type DayPressedAction = {| type: typeof EDIT_PLANNED_DAY_PRESSED |}

export type AnyEditPlannedTransactionDialogAction =
  {| type: typeof EDIT_PLANNED_TRANSACTION_CLOSE_DIALOG |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_CONFIRM_BP |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_REPEAT_EVERY_MONTH_PRESSED |}
  | OpenPlannedTransactionAction
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_AMOUNT_CHANGED, amount: number |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_COMMENT_CHANGED, comment: string |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_TEXT_CHANGED, tagsText: string |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_CHANGED, tags: Array<string> |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_CANCEL_BP |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_DIALOG_CURRENCY_PRESS |}
  | DayPressedAction

export const
  onDialogConfirmBtnPressAC = () => ({ type: EDIT_PLANNED_TRANSACTION_DIALOG_CONFIRM_BP }),
  onDialogCancelBtnPressAC = () => ({ type: EDIT_PLANNED_TRANSACTION_DIALOG_CANCEL_BP }),
  onAmountChangedAC = (amount: number) => ({
    type: EDIT_PLANNED_TRANSACTION_DIALOG_AMOUNT_CHANGED,
    amount,
  }),
  onCommentChangedAC = (amount: number) => ({
    type: EDIT_PLANNED_TRANSACTION_DIALOG_COMMENT_CHANGED,
    amount,
  }),
  onCurrencyPressAC = () => ({ type: EDIT_PLANNED_TRANSACTION_DIALOG_CURRENCY_PRESS }),
  openEditPlannedTransactionDialogAC = (transactionId: string): OpenPlannedTransactionAction => ({
    type: OPEN_EDIT_PLANNED_TRANSACTION_DIALOG,
    transactionId,
  }),
  onTagsChangedAC = (tags: Array<string>) => ({
    type: EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_CHANGED,
    tags,
  }),
  onTagsTextChangedAC = (tagsText: string) => ({
    type: EDIT_PLANNED_TRANSACTION_DIALOG_TAGS_TEXT_CHANGED,
    tagsText,
  }),
  onRepeatEveryMonthToggleAC = () => ({
    type: EDIT_PLANNED_TRANSACTION_DIALOG_REPEAT_EVERY_MONTH_PRESSED,
  }),
  onDayPressAC = (): DayPressedAction => ({ type: EDIT_PLANNED_DAY_PRESSED })
