/* @flow */

export const
  SEND_BACKUP_NOW_BP: 'SEND_BACKUP_NOW_BP' = 'SEND_BACKUP_NOW_BP',
  RESTORE_ACCOUNT_FROM_BACKUP_BP: 'RESTORE_ACCOUNT_FROM_BACKUP_BP' =
    'RESTORE_ACCOUNT_FROM_BACKUP_BP',
  IMPORT_FROM_DREBEDENGI_BP: 'IMPORT_FROM_DREBEDENGI_BP' = 'IMPORT_FROM_DREBEDENGI_BP',
  BACKUP_EMAIL_CHANGED: 'BACKUP_EMAIL_CHANGED' = 'BACKUP_EMAIL_CHANGED',
  RESTORE_FROM_BACKUP_START: 'RESTORE_FROM_BACKUP_START' = 'RESTORE_FROM_BACKUP_START',
  RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE_DONE: 'RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE_DONE' = // eslint-disable-line max-len
    'RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE_DONE',
  RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE: 'RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE' =
    'RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE',
  RESTORE_FROM_BACKUP_FAILURE: 'RESTORE_FROM_BACKUP_FAILURE' = 'RESTORE_FROM_BACKUP_FAILURE'

export type AnyBackupModuleAction =
  {| type: typeof SEND_BACKUP_NOW_BP |}
  | {| type: typeof RESTORE_ACCOUNT_FROM_BACKUP_BP |}
  | {| type: typeof IMPORT_FROM_DREBEDENGI_BP |}
  | {| type: typeof BACKUP_EMAIL_CHANGED, text: string |}
  | {| type: typeof RESTORE_FROM_BACKUP_START |}
  | {| type: typeof RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE_DONE |}
  | {| type: typeof RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE |}
  | {| type: typeof RESTORE_FROM_BACKUP_FAILURE |}

export const
  sendBackupNowBtnPressedAC = () => ({ type: SEND_BACKUP_NOW_BP }),
  restoreAccountFromBackupBtnPressedAC = () => ({ type: RESTORE_ACCOUNT_FROM_BACKUP_BP }),
  importFromDrebeDengiBtnPressedAC = () => ({ type: IMPORT_FROM_DREBEDENGI_BP }),
  backupEmailInputChangedAC = (text: string) => ({ type: BACKUP_EMAIL_CHANGED, text }),
  restoreFromBackupStartAC = () => ({ type: RESTORE_FROM_BACKUP_START }),
  restoreFromBackupSettingDataToFirebaseAC =
    () => ({ type: RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE }),
  restoreFromBackupSettingDataToFirebaseDoneAC =
    () => ({ type: RESTORE_FROM_BACKUP_SETTING_DATA_TO_FIREBASE_DONE }),
  restoreFromBackupFailureAC = () => ({ type: RESTORE_FROM_BACKUP_FAILURE })
