target 'mfg' do
  platform :ios, '9.0'

  react_native_path = "../node_modules/react-native"

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  "# Pods for AppCenter"
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  
end
