/* @flow */
/* eslint-disable max-len */
export const
  OVERVIEW_STORAGES_ACTIONS_DIALOG_EDIT_STORAGE_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_EDIT_STORAGE_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_EDIT_STORAGE_BP',
  OVERVIEW_STORAGE_ACTIONS_DIALOG_CLOSED: 'OVERVIEW_STORAGE_ACTIONS_DIALOG_CLOSED' =
    'OVERVIEW_STORAGE_ACTIONS_DIALOG_CLOSED',
  OVERVIEW_STORAGES_ACTIONS_DIALOG_SORT_STORAGE_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_SORT_STORAGE_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_SORT_STORAGE_BP',
  OVERVIEW_STORAGES_ACTIONS_DIALOG_HIDE_STORAGE_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_HIDE_STORAGE_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_HIDE_STORAGE_BP',
  OVERVIEW_STORAGES_ACTIONS_DIALOG_SHOW_HIDDEN_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_SHOW_HIDDEN_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_SHOW_HIDDEN_BP',
  OVERVIEW_STORAGES_ACTIONS_DIALOG_ADD_STORAGE_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_ADD_STORAGE_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_ADD_STORAGE_BP',
  OVERVIEW_STORAGES_ACTIONS_DIALOG_DONT_SHOW_IN_SECURE_MODE_STORAGE_BP: 'OVERVIEW_STORAGES_ACTIONS_DIALOG_DONT_SHOW_IN_SECURE_MODE_STORAGE_BP' =
    'OVERVIEW_STORAGES_ACTIONS_DIALOG_DONT_SHOW_IN_SECURE_MODE_STORAGE_BP'

export type AnyStoragesActionsDialogAction =
  {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_EDIT_STORAGE_BP |}
  | {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_SORT_STORAGE_BP |}
  | {| type: typeof OVERVIEW_STORAGE_ACTIONS_DIALOG_CLOSED |}
  | {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_HIDE_STORAGE_BP |}
  | {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_SHOW_HIDDEN_BP |}
  | {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_ADD_STORAGE_BP |}
  | {| type: typeof OVERVIEW_STORAGES_ACTIONS_DIALOG_DONT_SHOW_IN_SECURE_MODE_STORAGE_BP |}

export const
  overviewScreenStoragesActionsDialogEditStorageBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_EDIT_STORAGE_BP }),
  overviewScreenStoragesActionsDialogSortStorageBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_SORT_STORAGE_BP }),
  overviewScreenStoragesActionsDialogHideStorageBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_HIDE_STORAGE_BP }),
  overviewScreenStoragesActionsDialogDontShowInSecureModeStorageBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_DONT_SHOW_IN_SECURE_MODE_STORAGE_BP }),
  overviewScreenStoragesActionsDialogAddStoragePressBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_ADD_STORAGE_BP }),
  overviewScreenStoragesActionsDialogShowHiddenStorageBPAC = () =>
    ({ type: OVERVIEW_STORAGES_ACTIONS_DIALOG_SHOW_HIDDEN_BP })
