/* @flow */
/* eslint-disable max-len */
import type { CurrencyCode } from '../../const'
import type { CountryCode } from './countryReferenceMap';

type Decimals = 0 | 1 | 2 | 3
type Emoji = string
type DefaultValue = number
type Name = string
type CountryName = string
type CurrencyReference = [Decimals, DefaultValue, Name, Array<[CountryCode, Emoji, CountryName]>]

type CurrencyReferenceMap = { [key: CurrencyCode]: CurrencyReference }

const currencyReferenceMap: CurrencyReferenceMap = {
  'AED': [2, 3.673097, 'UAE dirham', [['AE', '🇦🇪', 'United Arab Emirates']]],
  'AFN': [2, 68.133, 'Afghan afghani', [['AF', '🇦🇫', 'Afghanistan']]],
  'ALL': [2, 112.473203, 'Albanian lek', [['AL', '🇦🇱', 'Albania']]],
  'AMD': [2, 476.565753, 'Armenian dram', [['AM', '🇦🇲', 'Armenia']]],
  'ANG': [2, 1.772959, 'Netherlands Antillean guilder', [['CW', '🇨🇼', 'Curacao'], ['SX', '🇸🇽', 'Sint Maarten']]],
  'AOA': [2, 165.9195, 'Angolan kwanza', [['AO', '🇦🇴', 'Angola']]],
  'ARS': [2, 17.7025, 'Argentine peso', [['AR', '🇦🇷', 'Argentina']]],
  'AUD': [2, 1.274239, 'Australian dollar', [['AU', '🇦🇺', 'Australia'], ['CC', '🇨🇨', 'Cocos (Keeling) Islands'], ['CX', '🇨🇽', 'Christmas Island'], ['HM', '🇭🇲', 'Heard Island And McDonald Islands'], ['KI', '🇰🇮', 'Kiribati'], ['NF', '🇳🇫', 'Norfolk Island'], ['NR', '🇳🇷', 'Nauru'], ['TV', '🇹🇻', 'Tuvalu']]],
  'AWG': [2, 1.794996, 'Aruban florin', [['AW', '🇦🇼', 'Aruba']]],
  'AZN': [2, 1.6855, 'Azerbaijani manat', [['AZ', '🇦🇿', 'Azerbaijan']]],
  'BAM': [2, 1.661692, 'Bosnia and Herzegovina convertible mark', [['BA', '🇧🇦', 'Bosnia & Herzegovina']]],
  'BBD': [2, 2, 'Barbados dollar', [['BB', '🇧🇧', 'Barbados']]],
  'BDT': [2, 80.5755, 'Bangladeshi taka', [['BD', '🇧🇩', 'Bangladesh']]],
  'BGN': [2, 1.662145, 'Bulgarian lev', [['BG', '🇧🇬', 'Bulgaria']]],
  'BHD': [3, 0.37714, 'Bahraini dinar', [['BH', '🇧🇭', 'Bahrain']]],
  'BIF': [0, 1730.5, 'Burundian franc', [['BI', '🇧🇮', 'Burundi']]],
  'BMD': [2, 1, 'Bermudian dollar', [['BM', '🇧🇲', 'Bermuda']]],
  'BND': [2, 1.363396, 'Brunei dollar', [['BN', '🇧🇳', 'Brunei Darussalam']]],
  'BOB': [2, 6.9381, 'Boliviano', [['BO', '🇧🇴', 'Bolivia, Plurinational State Of']]],
  'BRL': [2, 3.1753, 'Brazilian real', [['BR', '🇧🇷', 'Brazil']]],
  'BSD': [2, 1, 'Bahamian dollar', [['BS', '🇧🇸', 'Bahamas']]],
  'BTN': [2, 63.985001, 'Bhutanese ngultrum', [['BT', '🇧🇹', 'Bhutan']]],
  'BWP': [2, 10.237114, 'Botswana pula', [['BW', '🇧🇼', 'Botswana']]],
  'BZD': [2, 2.007846, 'Belize dollar', [['BZ', '🇧🇿', 'Belize']]],
  'CAD': [2, 1.274073, 'Canadian dollar', [['CA', '🇨🇦', 'Canada']]],
  'CDF': [2, 1587.701613, 'Congolese franc', [['CD', '🇨🇩', 'Democratic Republic Of Congo']]],
  'CHF': [2, 0.960286, 'Swiss franc', [['CH', '🇨🇭', 'Switzerland'], ['LI', '🇱🇮', 'Liechtenstein']]],
  'CLF': [0, 0.024158, 'Unidad de Fomento', []],
  'CLP': [0, 647.927985, 'Chilean peso', [['CL', '🇨🇱', 'Chile']]],
  'CNY': [2, 6.667106, 'Chinese yuan', [['CN', '🇨🇳', 'China']]],
  'COP': [2, 2990.4, 'Colombian peso', [['CO', '🇨🇴', 'Colombia']]],
  'CRC': [2, 574.945, 'Costa Rican colon', [['CR', '🇨🇷', 'Costa Rica']]],
  'CUC': [2, 1, 'Cuban convertible peso', [['C2', '🇨🇺', 'Cuba expat']]],
  'CUP': [2, 25.75, 'Cuban peso', [['CU', '🇨🇺', 'Cuba local']]],
  'CVE': [0, 94.1, 'Cape Verde escudo', [['CV', '🇨🇻', 'Cabo Verde']]],
  'CZK': [2, 22.233494, 'Czech koruna', [['CZ', '🇨🇿', 'Czech Republic']]],
  'DJF': [0, 178.935, 'Djiboutian franc', [['DJ', '🇩🇯', 'Djibouti']]],
  'DKK': [2, 6.31677, 'Danish krone', [['DK', '🇩🇰', 'Denmark'], ['FO', '🇫🇴', 'Faroe Islands'], ['GL', '🇬🇱', 'Greenland']]],
  'DOP': [2, 47.009, 'Dominican peso', [['DO', '🇩🇴', 'Dominican Republic']]],
  'DZD': [2, 109.615, 'Algerian dinar', [['DZ', '🇩🇿', 'Algeria']]],
  'EGP': [2, 17.771, 'Egyptian pound', [['EG', '🇪🇬', 'Egypt']]],
  'ERN': [2, 15.278472, 'Eritrean nakfa', [['ER', '🇪🇷', 'Eritrea']]],
  'ETB': [2, 23.238179, 'Ethiopian birr', [['ET', '🇪🇹', 'Ethiopia']]],
  'EUR': [2, 0.849228, 'Euro', [['AD', '🇦🇩', 'Andorra'], ['AT', '🇦🇹', 'Austria'], ['AX', '🇦🇽', 'Åland Islands'], ['BE', '🇧🇪', 'Belgium'], ['BL', '🇧🇱', 'Saint Barthélemy'], ['CY', '🇨🇾', 'Cyprus'], ['DE', '🇩🇪', 'Germany'], ['EE', '🇪🇪', 'Estonia'], ['ES', '🇪🇸', 'Spain'], ['FI', '🇫🇮', 'Finland'], ['FR', '🇫🇷', 'France'], ['GF', '🇬🇫', 'French Guiana'], ['GP', '🇬🇵', 'Guadeloupe'], ['GR', '🇬🇷', 'Greece'], ['IE', '🇮🇪', 'Ireland'], ['IT', '🇮🇹', 'Italy'], ['LT', '🇱🇹', 'Lithuania'], ['LU', '🇱🇺', 'Luxembourg'], ['LV', '🇱🇻', 'Latvia'], ['MC', '🇲🇨', 'Monaco'], ['ME', '🇲🇪', 'Montenegro'], ['MF', '🇲🇫', 'Saint Martin'], ['MQ', '🇲🇶', 'Martinique'], ['MT', '🇲🇹', 'Malta'], ['NL', '🇳🇱', 'Netherlands'], ['PM', '🇵🇲', 'Saint Pierre And Miquelon'], ['PT', '🇵🇹', 'Portugal'], ['RE', '🇷🇪', 'Reunion'], ['SI', '🇸🇮', 'Slovenia'], ['SM', '🇸🇲', 'San Marino'], ['TF', '🇹🇫', 'French Southern Territories'], ['VA', '🇻🇦', 'Vatican City State'], ['XK', '', 'Kosovo'], ['YT', '🇾🇹', 'Mayotte']]],
  'FJD': [2, 2.018197, 'Fiji dollar', [['FJ', '🇫🇯', 'Fiji']]],
  'FKP': [2, 0.769602, 'Falkland Islands pound', [['FK', '🇫🇰', 'Falkland Islands']]],
  'GBP': [2, 0.769602, 'Pound sterling', [['GB', '🇬🇧', 'United Kingdom'], ['GG', '🇬🇬', 'Guernsey'], ['GS', '🇬🇸', 'South Georgia And The South Sandwich Islands'], ['IM', '🇮🇲', 'Isle Of Man'], ['JE', '🇯🇪', 'Jersey']]],
  'GEL': [2, 2.390225, 'Georgian lari', []],
  'GHS': [2, 4.400448, 'Ghanaian cedi', [['GH', '🇬🇭', 'Ghana']]],
  'GIP': [2, 0.769602, 'Gibraltar pound', [['GI', '🇬🇮', 'Gibraltar']]],
  'GMD': [2, 46.05, 'Gambian dalasi', [['GM', '🇬🇲', 'Gambia']]],
  'GNF': [0, 8950.5, 'Guinean franc', [['GN', '🇬🇳', 'Guinea']]],
  'GTQ': [2, 7.2474, 'Guatemalan quetzal', [['GT', '🇬🇹', 'Guatemala']]],
  'GYD': [2, 206.977485, 'Guyanese dollar', [['GY', '🇬🇾', 'Guyana']]],
  'HKD': [2, 7.817401, 'Hong Kong dollar', [['HK', '🇭🇰', 'Hong Kong']]],
  'HNL': [2, 23.277305, 'Honduran lempira', [['HN', '🇭🇳', 'Honduras']]],
  'HRK': [2, 6.2847, 'Croatian kuna', [['HR', '🇭🇷', 'Croatia']]],
  'HTG': [2, 63.551106, 'Haitian gourde', [['HT', '🇭🇹', 'Haiti']]],
  'HUF': [2, 259.695, 'Hungarian forint', [['HU', '🇭🇺', 'Hungary']]],
  'IDR': [2, 13369, 'Indonesian rupiah', [['ID', '🇮🇩', 'Indonesia']]],
  'ILS': [2, 3.588065, 'Israeli new shekel', [['IL', '🇮🇱', 'Israel']]],
  'INR': [2, 64.205, 'Indian rupee', [['IN', '🇮🇳', 'India']]],
  'IQD': [3, 1163.4, 'Iraqi dinar', [['IQ', '🇮🇶', 'Iraq']]],
  'IRR': [0, 32840.2837, 'Iranian rial', [['IR', '🇮🇷', 'Iran, Islamic Republic Of']]],
  'ISK': [0, 105.699654, 'Icelandic króna', [['IS', '🇮🇸', 'Iceland']]],
  'JMD': [2, 127.37, 'Jamaican dollar', [['JM', '🇯🇲', 'Jamaica']]],
  'JOD': [3, 0.7085, 'Jordanian dinar', [['JO', '🇯🇴', 'Jordan'], ['PS', '🇵🇸', 'Palestinian Territory, Occupied']]],
  'JPY': [0, 108.97828115, 'Japanese yen', [['JP', '🇯🇵', 'Japan']]],
  'KES': [2, 103.855, 'Kenyan shilling', [['KE', '🇰🇪', 'Kenya']]],
  'KGS': [2, 69.348067, 'Kyrgyzstani som', [['KG', '🇰🇬', 'Kyrgyzstan']]],
  'KHR': [2, 4091.75, 'Cambodian riel', [['KH', '🇰🇭', 'Cambodia']]],
  'KMF': [0, 419.219527, 'Comoro franc', [['KM', '🇰🇲', 'Comoros']]],
  'KPW': [0, 900.09, 'North Korean won', [['KP', '🇰🇵', "Korea, Democratic People's Republic Of"]]],
  'KRW': [0, 1146.03, 'South Korean won', [['KR', '🇰🇷', 'Korea, Republic Of']]],
  'KWD': [3, 0.301944, 'Kuwaiti dinar', [['KW', '🇰🇼', 'Kuwait']]],
  'KYD': [2, 0.83011, 'Cayman Islands dollar', [['KY', '🇰🇾', 'Cayman Islands']]],
  'KZT': [2, 331.53, 'Kazakhstani tenge', [['KZ', '🇰🇿', 'Kazakhstan']]],
  'LAK': [0, 8248.9, 'Lao kip', [['LA', '🇱🇦', "Lao People's Democratic Republic"]]],
  'LBP': [0, 1502.3, 'Lebanese pound', [['LB', '🇱🇧', 'Lebanon']]],
  'LKR': [2, 152.625, 'Sri Lankan rupee', [['LK', '🇱🇰', 'Sri Lanka']]],
  'LRD': [2, 115.005853, 'Liberian dollar', [['LR', '🇱🇷', 'Liberia']]],
  'LSL': [2, 13.322243, 'Lesotho loti', [['LS', '🇱🇸', 'Lesotho']]],
  'LYD': [3, 1.361194, 'Libyan dinar', [['LY', '🇱🇾', 'Libya']]],
  'MAD': [2, 9.466, 'Moroccan dirham', [['EH', '🇪🇭', 'Western Sahara'], ['MA', '🇲🇦', 'Morocco']]],
  'MDL': [2, 17.839711, 'Moldovan leu', [['MD', '🇲🇩', 'Moldova']]],
  'MGA': [0, 2978.2, 'Malagasy ariary', [['MG', '🇲🇬', 'Madagascar']]],
  'MKD': [0, 52.311, 'Macedonian denar', [['MK', '🇲🇰', 'Macedonia, The Former Yugoslav Republic Of']]],
  'MMK': [0, 1358.6, 'Myanma kyat', [['MM', '🇲🇲', 'Myanmar']]],
  'MNT': [2, 2437.5, 'Mongolian tugrik', [['MN', '🇲🇳', 'Mongolia']]],
  'MOP': [2, 8.018039, 'Macanese pataca', [['MO', '🇲🇴', 'Macao']]],
  'MRO': [0, 362.831637, 'Mauritanian ouguiya', [['MR', '🇲🇷', 'Mauritania']]],
  'MUR': [2, 33.0515, 'Mauritian rupee', [['MU', '🇲🇺', 'Mauritius']]],
  'MVR': [2, 15.450233, 'Maldivian rufiyaa', [['MV', '🇲🇻', 'Maldives']]],
  'MWK': [2, 725.047458, 'Malawian kwacha', [['MW', '🇲🇼', 'Malawi']]],
  'MXN': [2, 17.971135, 'Mexican peso', [['MX', '🇲🇽', 'Mexico']]],
  'MYR': [2, 4.295442, 'Malaysian ringgit', [['MY', '🇲🇾', 'Malaysia']]],
  'MZN': [2, 61.275, 'Mozambican metical', [['MZ', '🇲🇿', 'Mozambique']]],
  'NAD': [2, 13.322243, 'Namibian dollar', [['NA', '🇳🇦', 'Namibia']]],
  'NGN': [2, 363.81, 'Nigerian naira', [['NG', '🇳🇬', 'Nigeria']]],
  'NIO': [2, 29.744983, 'Nicaraguan córdoba', [['NI', '🇳🇮', 'Nicaragua']]],
  'NOK': [2, 7.958905, 'Norwegian krone', [['BV', '🇧🇻', 'Bouvet Island'], ['NO', '🇳🇴', 'Norway'], ['SJ', '🇸🇯', 'Svalbard And Jan Mayen']]],
  'NPR': [2, 102.085, 'Nepalese rupee', [['NP', '🇳🇵', 'Nepal']]],
  'NZD': [2, 1.375961, 'New Zealand dollar', [['CK', '🇨🇰', 'Cook Islands'], ['NU', '🇳🇺', 'Niue'], ['NZ', '🇳🇿', 'New Zealand'], ['PN', '🇵🇳', 'Pitcairn'], ['TK', '🇹🇰', 'Tokelau']]],
  'OMR': [3, 0.384975, 'Omani rial', [['OM', '🇴🇲', 'Oman']]],
  'PAB': [2, 1, 'Panamanian balboa', [['PA', '🇵🇦', 'Panama']]],
  'PEN': [2, 3.24801, 'Peruvian nuevo sol', [['PE', '🇵🇪', 'Peru']]],
  'PGK': [2, 3.168962, 'Papua New Guinean kina', [['PG', '🇵🇬', 'Papua New Guinea']]],
  'PHP': [2, 51.0275, 'Philippine peso', [['PH', '🇵🇭', 'Philippines']]],
  'PKR': [2, 104.945, 'Pakistani rupee', [['PK', '🇵🇰', 'Pakistan']]],
  'PLN': [2, 3.635328, 'Polish złoty', [['PL', '🇵🇱', 'Poland']]],
  'PYG': [0, 5557.65, 'Paraguayan guaraní', [['PY', '🇵🇾', 'Paraguay']]],
  'QAR': [2, 3.640877, 'Qatari riyal', [['QA', '🇶🇦', 'Qatar']]],
  'RON': [2, 3.886084, 'Romanian new leu', [['RO', '🇷🇴', 'Romania']]],
  'RSD': [2, 101.746502, 'Serbian dinar', [['RS', '🇷🇸', 'Serbia']]],
  'RUB': [2, 60.0243, 'Russian rouble', [['RU', '🇷🇺', 'Russian Federation']]],
  'RWF': [0, 825.095, 'Rwandan franc', [['RW', '🇷🇼', 'Rwanda']]],
  'SAR': [2, 3.74995, 'Saudi riyal', [['SA', '🇸🇦', 'Saudi Arabia']]],
  'SBD': [2, 7.748625, 'Solomon Islands dollar', [['SB', '🇸🇧', 'Solomon Islands']]],
  'SCR': [2, 13.485424, 'Seychelles rupee', [['SC', '🇸🇨', 'Seychelles']]],
  'SDG': [2, 6.650467, 'Sudanese pound', [['SD', '🇸🇩', 'Sudan']]],
  'SEK': [2, 8.131326, 'Swedish krona/kronor', [['SE', '🇸🇪', 'Sweden']]],
  'SGD': [2, 1.363143, 'Singapore dollar', [['SG', '🇸🇬', 'Singapore']]],
  'SHP': [2, 0.769602, 'Saint Helena pound', [['SH', '🇸🇭', 'Saint Helena, Ascension And Tristan Da Cunha']]],
  'SLL': [0, 7500.75, 'Sierra Leonean leone', [['SL', '🇸🇱', 'Sierra Leone']]],
  'SOS': [2, 576.205, 'Somali shilling', [['SO', '🇸🇴', 'Somalia']]],
  'SRD': [2, 7.438, 'Surinamese dollar', [['SR', '🇸🇷', 'Suriname']]],
  'SSP': [2, 125.879111, 'South Sudanese pound', [['SS', '🇸🇸', 'South Sudan']]],
  'STD': [0, 20806.41915, 'São Tomé and Príncipe dobra', [['ST', '🇸🇹', 'Sao Tome and Principe']]],
  'SYP': [2, 515.666667, 'Syrian pound', [['SY', '🇸🇾', 'Syrian Arab Republic']]],
  'SZL': [2, 13.323972, 'Swazi lilangeni', [['SZ', '🇸🇿', 'Swaziland']]],
  'THB': [2, 33.260179, 'Thai baht', [['TH', '🇹🇭', 'Thailand']]],
  'TJS': [2, 8.775807, 'Tajikistani somoni', [['TJ', '🇹🇯', 'Tajikistan']]],
  'TMT': [2, 3.499986, 'Turkmenistani manat', [['TM', '🇹🇲', 'Turkmenistan']]],
  'TND': [3, 2.4051, 'Tunisian dinar', [['TN', '🇹🇳', 'Tunisia']]],
  'TOP': [2, 2.190219, 'Tongan paʻanga', [['TO', '🇹🇴', 'Tonga']]],
  'TRY': [2, 3.546617, 'Turkish lira', [['TR', '🇹🇷', 'Turkey']]],
  'TTD': [2, 6.709554, 'Trinidad and Tobago dollar', [['TT', '🇹🇹', 'Trinidad And Tobago']]],
  'TWD': [2, 30.3695, 'New Taiwan dollar', [['TW', '🇹🇼', 'Taiwan']]],
  'TZS': [2, 2238.8, 'Tanzanian shilling', [['TZ', '🇹🇿', 'Tanzania, United Republic Of']]],
  'UAH': [2, 25.579, 'Ukrainian hryvnia', [['UA', '🇺🇦', 'Ukraine']]],
  'UGX': [2, 3596.05, 'Ugandan shilling', [['UG', '🇺🇬', 'Uganda']]],
  'USD': [2, 1, 'United States dollar', [['AS', '🇦🇸', 'American Samoa'], ['EC', '🇪🇨', 'Ecuador'], ['FM', '🇫🇲', 'Micronesia, Federated States Of'], ['GU', '🇬🇺', 'Guam'], ['IO', '🇮🇴', 'British Indian Ocean Territory'], ['MH', '🇲🇭', 'Marshall Islands'], ['MP', '🇲🇵', 'Northern Mariana Islands'], ['PR', '🇵🇷', 'Puerto Rico'], ['PW', '🇵🇼', 'Palau'], ['SV', '🇸🇻', 'El Salvador'], ['TC', '🇹🇨', 'Turks And Caicos Islands'], ['TL', '🇹🇱', 'Timor-Leste, Democratic Republic of'], ['UM', '🇺🇲', 'United States Minor Outlying Islands'], ['US', '🇺🇸', 'United States'], ['VG', '🇻🇬', 'Virgin Islands (British)'], ['VI', '🇻🇮', 'Virgin Islands (US)']]],
  'UYU': [2, 28.5772, 'Uruguayan peso', [['UY', '🇺🇾', 'Uruguay']]],
  'UZS': [2, 4109.75, 'Uzbekistan som', [['UZ', '🇺🇿', 'Uzbekistan']]],
  'VEF': [2, 10.123556, 'Venezuelan bolívar fuerte', [['VE', '🇻🇪', 'Venezuela, Bolivarian Republic Of']]],
  'VND': [0, 22726, 'Vietnamese dong', [['VN', '🇻🇳', 'Viet Nam']]],
  'VUV': [0, 104.194999, 'Vanuatu vatu', [['VU', '🇻🇺', 'Vanuatu']]],
  'WST': [2, 2.44245, 'Samoan tala', [['WS', '🇼🇸', 'Samoa']]],
  'XAF': [0, 557.057085, 'CFA franc BEAC', [['CF', '🇨🇫', 'Central African Republic'], ['CG', '🇨🇬', 'Republic Of Congo'], ['CM', '🇨🇲', 'Cameroon'], ['GA', '🇬🇦', 'Gabon'], ['GQ', '🇬🇶', 'Equatorial Guinea'], ['TD', '🇹🇩', 'Chad']]],
  'XAG': [0, 0.05851889, 'Silver', []],
  'XAU': [0, 0.00077752, 'Gold', []],
  'XCD': [2, 2.70255, 'East Caribbean dollar', [['AG', '🇦🇬', 'Antigua And Barbuda'], ['DM', '🇩🇲', 'Dominica'], ['GD', '🇬🇩', 'Grenada'], ['KN', '🇰🇳', 'Saint Kitts And Nevis'], ['LC', '🇱🇨', 'Saint Lucia'], ['MS', '🇲🇸', 'Montserrat'], ['VC', '🇻🇨', 'Saint Vincent And The Grenadines']]],
  'XDR': [0, 0.71, 'Special drawing rights', []],
  'XOF': [0, 557.057085, 'CFA franc BCEAO', [['BF', '🇧🇫', 'Burkina Faso'], ['BJ', '🇧🇯', 'Benin'], ['CI', '🇨🇮', "Côte d'Ivoire"], ['GW', '🇬🇼', 'Guinea-bissau'], ['ML', '🇲🇱', 'Mali'], ['NE', '🇳🇪', 'Niger'], ['SN', '🇸🇳', 'Senegal'], ['TG', '🇹🇬', 'Togo']]],
  'XPD': [0, 0.00110805, 'Palladium', []],
  'XPF': [0, 101.339863, 'CFP franc', [['NC', '🇳🇨', 'New Caledonia'], ['PF', '🇵🇫', 'French Polynesia'], ['WF', '🇼🇫', 'Wallis And Futuna']]],
  'XPT': [0, 0.00101781, 'Platinum', []],
  'BTC': [0, 2.89599803E-4, 'BitCoin', []],
  'YER': [2, 250.306642, 'Yemeni rial', [['YE', '🇾🇪', 'Yemen']]],
  'ZAR': [2, 13.459922, 'South African rand', [['ZA', '🇿🇦', 'South Africa'], ['ZW', '🇿🇼', 'Zimbabwe']]],
  'ZMW': [2, 8.87006, 'Zambian kwacha', [['ZM', '🇿🇲', 'Zambia']]],
  'BTS': [0, 7.0303363025, 'BitShares', [['C0', '🏳️‍🌈', 'Crypto']]],
  'DASH': [0, 0.0028694008, 'Dash', [['C0', '🏳️‍🌈', 'Crypto']]],
  'DOGE': [0, 457.118325, 'DogeCoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'EAC': [0, 2437.9644, 'EarthCoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'EMC': [0, 0.840741804, 'Emercoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'ETH': [0, 0.0028860298, 'Ethereum', [['C0', '🏳️‍🌈', 'Crypto']]],
  'FCT': [0, 0.0369202701, 'Factom', [['C0', '🏳️‍🌈', 'Crypto']]],
  'FTC': [0, 15.3976698947, 'Feathercoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'LD': [0, 254.1, 'Linden Dollar', [['C0', '🏳️‍🌈', 'Crypto']]],
  'LTC': [0, 0.0128835848, 'LiteCoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'NMC': [0, 0.5115922404, 'Namecoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'NVC': [0, 0.3134525657, 'NovaCoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'NXT': [0, 9.4372815484, 'Nxt', [['C0', '🏳️‍🌈', 'Crypto']]],
  'PPC': [0, 0.5314042044, 'Peercoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'STR': [0, 47.8032235294, 'Stellar', [['C0', '🏳️‍🌈', 'Crypto']]],
  'VTC': [0, 1.2204738903, 'VertCoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'XMR': [0, 0.0081425859, 'Monero', [['C0', '🏳️‍🌈', 'Crypto']]],
  'XPM': [0, 2.5064747087, 'Primecoin', [['C0', '🏳️‍🌈', 'Crypto']]],
  'XRP': [0, 4.4210517026, 'Ripple', [['C0', '🏳️‍🌈', 'Crypto']]],
}

export { currencyReferenceMap };
