/* @flow */

export const
  EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_THIS: 'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_THIS' = // eslint-disable-line max-len
    'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_THIS',
  EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_ALL_FOLLOWING: 'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_ALL_FOLLOWING' = // eslint-disable-line max-len
    'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_ALL_FOLLOWING',
  EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_THIS: 'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_THIS' = // eslint-disable-line max-len
    'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_THIS',
  EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_ALL_FOLLOWING: 'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_ALL_FOLLOWING' = // eslint-disable-line max-len
    'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_ALL_FOLLOWING',
  EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_CLOSE: 'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_CLOSE' =
    'EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_CLOSE'

export type AnyEditPlannedTransactionActionsDialogAction =
  {| type: typeof EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_THIS |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_ALL_FOLLOWING |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_THIS |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_ALL_FOLLOWING |}
  | {| type: typeof EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_CLOSE |}


export const
  deleteThisPressAC = () => ({ type: EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_THIS }),
  deleteAllFollowingPressAC = () =>
    ({ type: EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_DELETE_ALL_FOLLOWING }),
  editThisPressAC = () => ({ type: EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_THIS }),
  editAllFollowingPressAC = () =>
    ({ type: EDIT_PLANNED_TRANSACTION_ACTIONS_DIALOG_EDIT_ALL_FOLLOWING })
