/* @flow */

export const
  MIGRATION_BACKUP_ACCOUNT: 'MIGRATION_BACKUP_ACCOUNT' =
    'MIGRATION_BACKUP_ACCOUNT',
  MIGRATION_BACKUP_ACCOUNT_FAILURE: 'MIGRATION_BACKUP_ACCOUNT_FAILURE' =
    'MIGRATION_BACKUP_ACCOUNT_FAILURE',
  MIGRATION_APPLYING_MIGRATION: 'MIGRATION_APPLYING_MIGRATION' =
    'MIGRATION_APPLYING_MIGRATION',
  MIGRATION_SAVING_MIGRATION: 'MIGRATION_SAVING_MIGRATION' =
    'MIGRATION_SAVING_MIGRATION'

export type AnyMigrationAction =
  {| type: typeof MIGRATION_BACKUP_ACCOUNT |}
  | {| type: typeof MIGRATION_BACKUP_ACCOUNT_FAILURE |}
  | {| type: typeof MIGRATION_APPLYING_MIGRATION |}
  | {| type: typeof MIGRATION_SAVING_MIGRATION |}

export const
  backupAccountAC = () => ({ type: MIGRATION_BACKUP_ACCOUNT }),
  backupAccountFailureAC = () => ({ type: MIGRATION_BACKUP_ACCOUNT_FAILURE }),
  applyingMigrationAC = () => ({ type: MIGRATION_APPLYING_MIGRATION }),
  savingMigrationAC = () => ({ type: MIGRATION_SAVING_MIGRATION })
