/* @flow */

export const
  OVERVIEW_TO_LEND_MONEY_CLOSE_DIALOG = 'OVERVIEW_TO_LEND_MONEY_CLOSE_DIALOG',
  OVERVIEW_TO_LEND_MONEY_DIALOG_AMOUNT_CHANGED = 'OVERVIEW_TO_LEND_MONEY_DIALOG_AMOUNT_CHANGED',
  OVERVIEW_TO_LEND_MONEY_DIALOG_CONFIRM_BP = 'OVERVIEW_TO_LEND_MONEY_DIALOG_CONFIRM_BP',
  OVERVIEW_TO_LEND_MONEY_DIALOG_CANCEL_BP = 'OVERVIEW_TO_LEND_MONEY_DIALOG_CANCEL_BP',
  OVERVIEW_TO_LEND_MONEY_DIALOG_IS_RELIABLE_PRESSED
    = 'OVERVIEW_TO_LEND_MONEY_DIALOG_IS_RELIABLE_PRESSED',
  OVERVIEW_TO_LEND_MONEY_STORAGE_TITLE_CHANGED = 'OVERVIEW_TO_LEND_MONEY_STORAGE_TITLE_CHANGED',
  TO_LEND_MONEY_DONE = 'TO_LEND_MONEY_DONE'

export type AnyToLendMoneyDialogAction =
  {| type: typeof OVERVIEW_TO_LEND_MONEY_CLOSE_DIALOG |}
  | {| type: typeof OVERVIEW_TO_LEND_MONEY_DIALOG_AMOUNT_CHANGED, newAmount: number |}
  | {| type: typeof OVERVIEW_TO_LEND_MONEY_DIALOG_CONFIRM_BP |}
  | {| type: typeof OVERVIEW_TO_LEND_MONEY_DIALOG_CANCEL_BP |}
  | {| type: typeof OVERVIEW_TO_LEND_MONEY_DIALOG_IS_RELIABLE_PRESSED |}
  | {| type: typeof TO_LEND_MONEY_DONE |}
  | {| type: typeof OVERVIEW_TO_LEND_MONEY_STORAGE_TITLE_CHANGED, newTitle: string |}

export const
  onToLendMoneyDialogAmountChangedAC = (newAmount: number) => ({
    type: OVERVIEW_TO_LEND_MONEY_DIALOG_AMOUNT_CHANGED,
    newAmount,
  }),
  onLendToStorageTitleChangedAC = (newTitle: string) => ({
    type: OVERVIEW_TO_LEND_MONEY_STORAGE_TITLE_CHANGED,
    newTitle,
  }),
  onToLendMoneyDialogConfirmBtnPressAC = () => ({
    type: OVERVIEW_TO_LEND_MONEY_DIALOG_CONFIRM_BP,
  }),
  onToLendMoneyDialogCancelBtnPressAC = () => ({
    type: OVERVIEW_TO_LEND_MONEY_DIALOG_CANCEL_BP,
  }),
  toLendDialogIsReliablePressedAC = () => ({
    type: OVERVIEW_TO_LEND_MONEY_DIALOG_IS_RELIABLE_PRESSED,
  }),
  toLendMoneyDoneAC = () => ({
    type: TO_LEND_MONEY_DONE,
  })
