/* @flow */
/* eslint-disable max-len */
export const
  PLAN_SCREEN_CATEGORY_DIALOG_CLOSE: 'PLAN_SCREEN_CATEGORY_DIALOG_CLOSE' =
    'PLAN_SCREEN_CATEGORY_DIALOG_CLOSE',
  PLAN_SCREEN_CATEGORY_DIALOG_ADD_PLANNED_TRANSACTION: 'PLAN_SCREEN_CATEGORY_DIALOG_ADD_PLANNED_TRANSACTION' =
    'PLAN_SCREEN_CATEGORY_DIALOG_ADD_PLANNED_TRANSACTION',
  PLAN_SCREEN_CATEGORY_DIALOG_CONFIRM_BP: 'PLAN_SCREEN_CATEGORY_DIALOG_CONFIRM_BP' =
    'PLAN_SCREEN_CATEGORY_DIALOG_CONFIRM_BP',
  PLAN_SCREEN_CATEGORY_DIALOG_REPEAT_EVERY_MONTH_PRESSED: 'PLAN_SCREEN_CATEGORY_DIALOG_REPEAT_EVERY_MONTH_PRESSED' =
    'PLAN_SCREEN_CATEGORY_DIALOG_REPEAT_EVERY_MONTH_PRESSED',
  PLAN_SCREEN_CATEGORY_DIALOG_AMOUNT_CHANGED: 'PLAN_SCREEN_CATEGORY_DIALOG_AMOUNT_CHANGED' =
    'PLAN_SCREEN_CATEGORY_DIALOG_AMOUNT_CHANGED',
  PLAN_SCREEN_CATEGORY_DIALOG_PLANNED_TRANSACTION_PRESSED: 'PLAN_SCREEN_CATEGORY_DIALOG_PLANNED_TRANSACTION_PRESSED' =
    'PLAN_SCREEN_CATEGORY_DIALOG_PLANNED_TRANSACTION_PRESSED',
  PLAN_SCREEN_CATEGORY_DIALOG_DELETE_PRESSED: 'PLAN_SCREEN_CATEGORY_DIALOG_DELETE_PRESSED' =
    'PLAN_SCREEN_CATEGORY_DIALOG_DELETE_PRESSED',
  PLAN_SCREEN_CATEGORY_DIALOG_CURRENCY_PRESSED: 'PLAN_SCREEN_CATEGORY_DIALOG_CURRENCY_PRESSED' =
    'PLAN_SCREEN_CATEGORY_DIALOG_CURRENCY_PRESSED',
  PLAN_SCREEN_CATEGORY_EXTENDED_PLAN_PRESSED: 'PLAN_SCREEN_CATEGORY_EXTENDED_PLAN_PRESSED' =
    'PLAN_SCREEN_CATEGORY_EXTENDED_PLAN_PRESSED',
  PLAN_SCREEN_CATEGORY_DIALOG_CANCEL_BP: 'PLAN_SCREEN_CATEGORY_DIALOG_CANCEL_BP' =
    'PLAN_SCREEN_CATEGORY_DIALOG_CANCEL_BP'


type PlanCategoryDialogConfirmBtnPressAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_CONFIRM_BP |}
type PlanCategoryDialogCancelBPAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_CANCEL_BP |}
type PlanCategoryRepeatEveryMonthPressedAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_REPEAT_EVERY_MONTH_PRESSED |}
type PlanCategoryDeletePressedAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_DELETE_PRESSED |}
type PlanCategoryAmountChangedAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_AMOUNT_CHANGED, amount: number |}
type PlanCategoryAddPlannedTransactionPressAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_ADD_PLANNED_TRANSACTION |}
type PlanCategoryCurrencyPressedAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_CURRENCY_PRESSED |}
type PlanCategoryExtendedPlanPressedAction = {| type: typeof PLAN_SCREEN_CATEGORY_EXTENDED_PLAN_PRESSED |}
type PlanCategoryPlannedTransactionPressedAction = {| type: typeof PLAN_SCREEN_CATEGORY_DIALOG_PLANNED_TRANSACTION_PRESSED, transactionId: string |}

export type AnyPlanCategoryDialogAction =
  | PlanCategoryDialogConfirmBtnPressAction
  | PlanCategoryDialogCancelBPAction
  | PlanCategoryRepeatEveryMonthPressedAction
  | PlanCategoryDeletePressedAction
  | PlanCategoryAmountChangedAction
  | PlanCategoryAddPlannedTransactionPressAction
  | PlanCategoryCurrencyPressedAction
  | PlanCategoryExtendedPlanPressedAction
  | PlanCategoryPlannedTransactionPressedAction

export const
  planCategoryDialogConfirmBtnPressAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_CONFIRM_BP }),
  planCategoryDialogCancelBPAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_CANCEL_BP }),
  planCategoryRepeatEveryMonthPressedAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_REPEAT_EVERY_MONTH_PRESSED }),
  planCategoryDeletePressedAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_DELETE_PRESSED }),
  planCategoryAmountChangedAC =
    (amount: number) => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_AMOUNT_CHANGED, amount }),
  planCategoryAddPlannedTransactionPressAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_ADD_PLANNED_TRANSACTION }),
  planCategoryCurrencyPressedAC = () => ({ type: PLAN_SCREEN_CATEGORY_DIALOG_CURRENCY_PRESSED }),
  planCategoryExtendedPlanPressedAC = () => ({ type: PLAN_SCREEN_CATEGORY_EXTENDED_PLAN_PRESSED }),
  planCategoryPlannedTransactionPressedAC = (transactionId: string) => ({
    type: PLAN_SCREEN_CATEGORY_DIALOG_PLANNED_TRANSACTION_PRESSED,
    transactionId,
  })
